-- FIRST VIEW JUST TO CHECK HOW DBT WORKS 
SELECT  SURFERS.SURFER_NAME, HOME_COUNTRY, STANCE, SURF_SPOT, SURF_SPOT_RATING
FROM SURFERS
LEFT JOIN SURF_SPOTS_FAV ON SURF_SPOTS_FAV.SURFER_NAME = SURFERS.SURFER_NAME
 WHERE SURFERS.SURFER_NAME LIKE 'KELLY%'
