
{{ config(materialized='table') }}

SELECT CAST(YEAR AS CHAR(4)) AS YEAR, JOBFAMILY, JOB, CAST(EMPLOYEEIDENTIFIER AS VARCHAR()) AS EMPLOYEEIDENTIFIER, TOTALSALARY, TOTALCOMPENSATION
FROM EMP_COMP_FULL_RAW WHERE  1 = 1 
AND JOB IN ('IS Engineer-Senior', 'IS Business Analyst-Senior', 'IS Engineer-Senior')
and yeartype = 'Calendar'
--ORDER BY 4 DESC